name: Docker 构建和推送

on:
  push:
    branches:
      - main
    tags:
      - latest

env:
  REGISTRY: docker.io
  IMAGE_NAME: findthewayxf/vps-value

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        uses: docker/login-action@v3 # 使用 v3 来支持 PAT
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }} # 使用 PAT，而不是密码

      - name: 构建和推送
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: latest # 只推送 'latest' 标签
          cache-from: type=gha
          cache-to: type=gha